/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// 合并后「YAK 编程文档」为单一文档树：编程教程与内置库参考统一在 docs 插件下。
// 侧边栏改为按目录结构自动生成，标签与顺序由各目录下的 _category_.json
// 与各文档的 frontmatter(sidebar_position / sidebar_label) 控制。
module.exports = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

