/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    "intro",
    "startup",
    {
      type: "category",
      label: "基础语法文档",
      items: [
        "yak-basic/cap3-stats-vars-and-exprs",
        "yak-basic/cap4-control-flow",
        "yak-basic/cap5-function",
        "yak-basic/cap6-1-concurrent-and-defer",
        "yak-basic/cap6-2-error-handling",
        "yak-basic/cap6-3-scope",
        "yak-basic/cap6-4-modules",
        "yak-basic/cap6-5-fuzztag",
        "yak-basic/cap7-buildin-functions",
        "yak-basic/cap8-1-http",
        "yak-basic/cap8-2-mitm",
        "yak-basic/cap8-3-port-n-service-scan",
        "yak-basic/cap8-4-yaml-poc",
        "yak-basic/cap8-5-java-hack",
      ],
    },
    {
      type: "category",
      label: "编程实战案例",
      items: [{ type: "autogenerated", dirName: "yakexamples" }],
    },
    {
      type: "category",
      label: "内置函数库文档",
      items: [{ type: "autogenerated", dirName: "buildinlibs" }],
    },
    {
      type: "category",
      label: "API 完全手册",
      items: [{ type: "autogenerated", dirName: "api" }],
    },
  ],
};

