/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

 module.exports = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
    // But you can create a sidebar manually
    tutorialSidebar: [
      "intro",
      {
        type: "category",
        label: "常见内置函数库文档",
        items: [{ type: "autogenerated", dirName: "buildinlibs" }],
      },
      {
        type: "category",
        label: "API 完全定义列表",
        items: [{ type: "autogenerated", dirName: "api" }],
      },
    ],
  };
  
  